<?xml version="1.0" encoding="utf-8"?><Database Name="AppTest" Class="DBAlarmaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=10.2.0.18;Initial Catalog=AppTest;Persist Security Info=True;User ID=AppTestUser" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="AppTestConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Alarma" Member="Alarmas">
    <Type Name="Alarma">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Titulo" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="NChar(500)" CanBeNull="true" />
      <Column Name="Hora" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </Type>
  </Table>
</Database>